const SIZES = {}

SIZES.BOARD_MARGIN = 20
SIZES.TOP_BAR_HEIGHT = 28
SIZES.BOTTOM_BAR_HEIGHT = 40
SIZES.CHROME_HEIGHT = SIZES.TOP_BAR_HEIGHT + SIZES.BOTTOM_BAR_HEIGHT + SIZES.BOARD_MARGIN

SIZES.EDITOR_WIDTH = 250
SIZES.RIGHT_BAR_WIDTH = 30
SIZES.CHROME_WIDTH = SIZES.EDITOR_WIDTH + SIZES.RIGHT_BAR_WIDTH + SIZES.BOARD_MARGIN

module.exports = { SIZES }
